In [ ]:
import tensorflow as tf
from tensorflow import keras
import numpy as np
import pandas as pd

In [ ]:
from google.colab import files
u = files.upload()
print(u)

Saving Data.csv to Data (1).csv
{'Data (1).csv': b'\xef\xbb\xbfbudget_million,worldwide_gross_million,genre,director_experience,runtime_min,release_season,sequel,Rating\r\n100,202,4,3,115,2,1,6.1\r\n100,337,3,5,157,1,1,7.2\r\n295,384,0,7,154,0,1,6.5\r\n250,761,0,6,119,0,1,6.2\r\n67,261,1,3,99,0,1,6.6\r\n100,41,4,4,132,0,0,6.5\r\n10,73,1,2,101,0,0,6.6\r\n85,547,2,3,94,2,1,6\r\n140,67,5,5,130,3,0,4.9\r\n180,73,2,4,102,1,0,5.5\r\n150,117,4,3,123,0,0,5.9\r\n195,439,0,3,127,0,1,6\r\n20,297,1,2,109,1,0,6\r\n2,52,1,2,125,1,1,6.7\r\n110,26,0,2,127,3,0,4.6\r\n50,8,0,2,111,0,0,4.3\r\n104,130,0,2,127,0,0,6.1\r\n200,156,4,9,206,1,0,7.6\r\n190,206,4,5,138,1,1,5.2\r\n38,269,1,2,110,1,1,5.9\r\n100,26,0,3,103,1,1,4.4\r\n200,1337,0,6,127,0,1,7.6\r\n250,859,0,6,161,1,1,6.7\r\n200,1699,2,4,100,0,1,7.6\r\n33,6,3,6,134,1,0,6.1\r\n100,453,4,7,104,1,1,6.8\r\n90,14,3,3,138,1,0,6.6\r\n100,690,2,4,140,0,1,8.6\r\n340,704,0,4,141,2,1,5.8\r\n200,271,0,3,144,0,0,6.7\r\n135,571,0,4,115,2,1,6.3\r\n220,206,0,3,105,1,1,5.6\r\n20,66,1,4,111,1,1,5\r\n155,370,0,3,122,0,1,6.5\r\n200,96,0,5,139,3,0,5.7\r\n145,1441,4,5,114,0,0,6.8\r\n65,351,5,3,119,0,1,7.1\r\n35,15,1,2,94,2,0,5\r\n35,91,1,3,95,3,0,5.9\r\n90,204,2,3,105,0,0,6.1\r\n177,1493,0,8,131,0,1,8.2\r\n75,167,0,3,104,2,0,5.1\r\n115,33,0,4,115,0,0,4.4\r\n20,45,6,1,102,0,0,6.1\r\n185,770,0,5,176,2,0,7.8\r\n200,226,2,4,100,0,0,6.1\r\n90,70,3,4,137,2,0,7\r\n125,134,0,3,130,2,1,5.8\r\n350,2320,5,9,192,3,1,7.6\r\n100,1362,2,4,92,2,0,7\r\n78,15,3,5,189,3,0,7.2\r\n8,5,1,1,84,3,0,3\r\n290,567,0,7,163,0,1,7.7\r\n80,100,0,2,116,3,0,3.8\r\n90,239,0,5,126,0,0,7.3\r\n68,171,1,3,130,0,0,6.8\r\n110,405,2,3,122,2,1,6.5\r\n120,11,3,8,138,1,0,5.1\r\n205,297,0,4,124,3,1,5.5\r\n150,1126,2,3,100,1,1,6.5\r\n80,939,2,5,87,0,1,6.5\r\n100,952,3,8,180,0,0,8.3\r\n100,440,0,5,169,2,1,7.7\r\n168,174,0,7,148,2,1,7.5\r\n'}

In [ ]:
df =pd.read_csv("/content/Data.csv")
df.head(2)

,budget_million,worldwide_gross_million,genre,director_experience,runtime_min,release_season,sequel,Rating
0,100,202,4,3,115,2,1,6.1
1,100,337,3,5,157,1,1,7.2

In [ ]:
x = df.drop(["Rating"] , axis=1)
y = df["Rating"]

In [ ]:
model = keras.Sequential([
    keras.layers.Dense(units=7, activation="relu" , input_shape=[7])
])
#model.add(keras.layers.Dense(units=7, activation="relu"))
model.add(keras.layers.Dense(units=1, activation="relu"))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.compile(optimizer="adam" , loss="mean_squared_error")

In [ ]:
model.summary()

Model: "sequential_13"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_27 (Dense)                │ (None, 7)              │            56 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_28 (Dense)                │ (None, 1)              │             8 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 64 (256.00 B)

 Trainable params: 64 (256.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(x , y ,epochs=500)

Epoch 1/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - loss: 38.7461
Epoch 2/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 37.4050
Epoch 3/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 38.0811
Epoch 4/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 37.7626
Epoch 5/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 37.6118
Epoch 6/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 37.1385
Epoch 7/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 36.7829
Epoch 8/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 36.7078
Epoch 9/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 36.7859
Epoch 10/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 36.6237
Epoch 11/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 36.4355
Epoch 12/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 36.5291
Epoch 13/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 37.1982
Epoch 14/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 36.4891
Epoch 15/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 36.0373
Epoch 16/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 36.6334
Epoch 17/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 36.6251
Epoch 18/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 36.2575
Epoch 19/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 36.1064
Epoch 20/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 36.5105
Epoch 21/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 36.2785
Epoch 22/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 35.7825
Epoch 23/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 36.8195
Epoch 24/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 36.4483
Epoch 25/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 36.0420
Epoch 26/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 35.9307
Epoch 27/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 36.1279
Epoch 28/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 36.1423
Epoch 29/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 36.2079
Epoch 30/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 36.0679
Epoch 31/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 35.7037
Epoch 32/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 35.6462
Epoch 33/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 35.7297
Epoch 34/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 35.6211
Epoch 35/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 35.6228
Epoch 36/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 35.6274
Epoch 37/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 35.5642
Epoch 38/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 35.6228
Epoch 39/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 35.7868
Epoch 40/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 35.7620
Epoch 41/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 35.5640
Epoch 42/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 35.6535
Epoch 43/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 35.5121
Epoch 44/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 35.5385
Epoch 45/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 35.8506
Epoch 46/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 35.5038
Epoch 47/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 35.4718
Epoch 48/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 35.9495
Epoch 49/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 35.5321
Epoch 50/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 35.7236
Epoch 51/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 35.5075
Epoch 52/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 35.4738
Epoch 53/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 35.3443
Epoch 54/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 35.3418
Epoch 55/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 35.2630
Epoch 56/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 35.1459
Epoch 57/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 35.0584
Epoch 58/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 35.0307
Epoch 59/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 34.8271
Epoch 60/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 34.4599
Epoch 61/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 34.0142
Epoch 62/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 33.4774
Epoch 63/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 32.9111
Epoch 64/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 32.5295
Epoch 65/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 32.2268
Epoch 66/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 31.6747
Epoch 67/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 31.2996
Epoch 68/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 30.8508
Epoch 69/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 30.5724
Epoch 70/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 30.2025
Epoch 71/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 30.1946
Epoch 72/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 30.0412
Epoch 73/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 29.4773
Epoch 74/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 29.1202
Epoch 75/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 28.7678
Epoch 76/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 28.4755
Epoch 77/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 28.2931
Epoch 78/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 27.9408
Epoch 79/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 27.7731
Epoch 80/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 27.3790
Epoch 81/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 26.9516
Epoch 82/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 26.9889
Epoch 83/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 26.3458
Epoch 84/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 25.9104
Epoch 85/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 25.5566
Epoch 86/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 25.4796
Epoch 87/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 24.9219
Epoch 88/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 24.6665
Epoch 89/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 24.0896
Epoch 90/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 23.6785
Epoch 91/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 23.4193
Epoch 92/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 23.0805
Epoch 93/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 22.4166
Epoch 94/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 22.3541
Epoch 95/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 22.2934
Epoch 96/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 21.6944
Epoch 97/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 21.0720
Epoch 98/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 20.9980
Epoch 99/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 20.1864
Epoch 100/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 19.9184
Epoch 101/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 19.3577
Epoch 102/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 18.7795
Epoch 103/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 18.1776
Epoch 104/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 18.0257
Epoch 105/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 16.8340
Epoch 106/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 16.5904
Epoch 107/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 15.1852
Epoch 108/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 14.1670
Epoch 109/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 13.6367
Epoch 110/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 11.3739
Epoch 111/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 10.5226
Epoch 112/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 9.9948
Epoch 113/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 8.7745
Epoch 114/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 7.7329
Epoch 115/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 6.8345
Epoch 116/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 6.4408
Epoch 117/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 5.6799
Epoch 118/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 5.1600
Epoch 119/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 4.8503
Epoch 120/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 4.1875
Epoch 121/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 4.0686
Epoch 122/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 3.8605
Epoch 123/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 3.2680
Epoch 124/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 3.0675
Epoch 125/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 2.9191
Epoch 126/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 2.6528
Epoch 127/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 2.4961
Epoch 128/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 2.3336
Epoch 129/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 2.2550
Epoch 130/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 2.1190
Epoch 131/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 2.0267
Epoch 132/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 1.9780
Epoch 133/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1.8954
Epoch 134/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 1.8768
Epoch 135/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 1.8212
Epoch 136/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 1.7278
Epoch 137/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1.7398
Epoch 138/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 1.7135
Epoch 139/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1.6038
Epoch 140/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 1.6239
Epoch 141/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 1.6202
Epoch 142/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1.6848
Epoch 143/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1.5391
Epoch 144/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1.4726
Epoch 145/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 1.4843
Epoch 146/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 1.4250
Epoch 147/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 1.4103
Epoch 148/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1.4359
Epoch 149/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1.3618
Epoch 150/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 1.3860
Epoch 151/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 1.3667
Epoch 152/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 1.3225
Epoch 153/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 1.3257
Epoch 154/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 1.2805
Epoch 155/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 1.3411
Epoch 156/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 1.2711
Epoch 157/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 1.2646
Epoch 158/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 1.2324
Epoch 159/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 1.2082
Epoch 160/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 1.2162
Epoch 161/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 1.1839
Epoch 162/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 1.1769
Epoch 163/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 1.1701
Epoch 164/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 1.2016
Epoch 165/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 1.1685
Epoch 166/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 1.1413
Epoch 167/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 1.1417
Epoch 168/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 1.1464
Epoch 169/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 1.1119
Epoch 170/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 1.1121
Epoch 171/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 1.1055
Epoch 172/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 1.1126
Epoch 173/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 1.0842
Epoch 174/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 1.0832
Epoch 175/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 1.0925
Epoch 176/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 1.1186
Epoch 177/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 1.1185
Epoch 178/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 1.0432
Epoch 179/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 1.0697
Epoch 180/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 1.1174
Epoch 181/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 1.0411
Epoch 182/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 1.0545
Epoch 183/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1.0544
Epoch 184/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1.0392
Epoch 185/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1.0300
Epoch 186/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1.0187
Epoch 187/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1.0417
Epoch 188/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 1.0059
Epoch 189/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.9925
Epoch 190/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1.0816
Epoch 191/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 1.0642
Epoch 192/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 1.0130
Epoch 193/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 1.0066
Epoch 194/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.9990
Epoch 195/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 1.0547
Epoch 196/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 1.0117
Epoch 197/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.9938
Epoch 198/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.9941
Epoch 199/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.9597
Epoch 200/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.9778
Epoch 201/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.9906
Epoch 202/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.9836
Epoch 203/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.9786
Epoch 204/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.9892
Epoch 205/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 1.0443
Epoch 206/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.9750
Epoch 207/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 1.0275
Epoch 208/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.9431
Epoch 209/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.9541
Epoch 210/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.9886
Epoch 211/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.9372
Epoch 212/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.9258
Epoch 213/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.9288
Epoch 214/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.9168
Epoch 215/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.9130
Epoch 216/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.9685
Epoch 217/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.9827
Epoch 218/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.9354
Epoch 219/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.9000
Epoch 220/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.9166
Epoch 221/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8997
Epoch 222/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.9191
Epoch 223/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.8940
Epoch 224/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.9470
Epoch 225/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.9257
Epoch 226/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8917
Epoch 227/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8896
Epoch 228/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8811
Epoch 229/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8863
Epoch 230/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.8797
Epoch 231/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8762
Epoch 232/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8893
Epoch 233/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.8914
Epoch 234/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.8727
Epoch 235/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.8857
Epoch 236/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.8684
Epoch 237/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.9386
Epoch 238/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.8714
Epoch 239/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.8989
Epoch 240/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.9109
Epoch 241/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.8585
Epoch 242/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.8994
Epoch 243/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8588
Epoch 244/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.9475
Epoch 245/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8465
Epoch 246/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.9132
Epoch 247/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.9294
Epoch 248/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.9019
Epoch 249/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8724
Epoch 250/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.8737
Epoch 251/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8613
Epoch 252/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.8358
Epoch 253/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.8780
Epoch 254/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.8791
Epoch 255/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.9084
Epoch 256/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8547
Epoch 257/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.9165
Epoch 258/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8563
Epoch 259/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.8509
Epoch 260/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.9227
Epoch 261/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.9132
Epoch 262/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.9414
Epoch 263/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8254
Epoch 264/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8868
Epoch 265/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.8268
Epoch 266/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.8936
Epoch 267/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.8482
Epoch 268/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8098
Epoch 269/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8828
Epoch 270/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.8136
Epoch 271/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8365
Epoch 272/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.8444
Epoch 273/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.9413
Epoch 274/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8696
Epoch 275/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.8849
Epoch 276/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8594
Epoch 277/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8525
Epoch 278/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8299
Epoch 279/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.8312
Epoch 280/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8358
Epoch 281/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8242
Epoch 282/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8610
Epoch 283/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.8109
Epoch 284/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.7989
Epoch 285/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.8118
Epoch 286/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 0.8522
Epoch 287/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.8252
Epoch 288/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.7905
Epoch 289/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.8424
Epoch 290/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.8091
Epoch 291/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.7932
Epoch 292/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.8480
Epoch 293/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 0.7835
Epoch 294/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.8198
Epoch 295/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.8258
Epoch 296/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7882
Epoch 297/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.8121
Epoch 298/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.8009
Epoch 299/500

In [ ]:
model0 = keras.Sequential([
    keras.layers.Dense(units=7, activation="relu" , input_shape=[7])
])
model0.add(keras.layers.Dense(units=7, activation="relu"))
model0.add(keras.layers.Dense(units=1, activation="relu"))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model0.compile(optimizer="adam" , loss="mean_squared_error")

In [ ]:
model0.summary()

Model: "sequential_15"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_31 (Dense)                │ (None, 7)              │            56 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_32 (Dense)                │ (None, 7)              │            56 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_33 (Dense)                │ (None, 1)              │             8 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 120 (480.00 B)

 Trainable params: 120 (480.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model0.fit(x , y ,epochs=500)

Epoch 1/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 50.0637
Epoch 2/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 45.5353
Epoch 3/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 42.5939
Epoch 4/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 39.0869
Epoch 5/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 37.1540
Epoch 6/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 35.4654
Epoch 7/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 34.5820
Epoch 8/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 33.7943
Epoch 9/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 33.4498
Epoch 10/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 33.2358
Epoch 11/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 33.0990
Epoch 12/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 33.0607
Epoch 13/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 32.8434
Epoch 14/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 32.6211
Epoch 15/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 32.3401
Epoch 16/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 32.0801
Epoch 17/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 31.7298
Epoch 18/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 31.5465
Epoch 19/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 31.4014
Epoch 20/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 31.2172
Epoch 21/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 31.1124
Epoch 22/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 30.9942
Epoch 23/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 30.8609
Epoch 24/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 30.6716
Epoch 25/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 30.5250
Epoch 26/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 30.3435
Epoch 27/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 30.2149
Epoch 28/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 29.9959
Epoch 29/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 29.8114
Epoch 30/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 29.6622
Epoch 31/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 29.5188
Epoch 32/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 29.3453
Epoch 33/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 29.2431
Epoch 34/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 29.1016
Epoch 35/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 28.9976
Epoch 36/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 28.9022
Epoch 37/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 28.7785
Epoch 38/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 28.6846
Epoch 39/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 28.5841
Epoch 40/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 28.5132
Epoch 41/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 28.4411
Epoch 42/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 28.3599
Epoch 43/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 28.3078
Epoch 44/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 28.2303
Epoch 45/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 28.1688
Epoch 46/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 28.1124
Epoch 47/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 28.0581
Epoch 48/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 27.9992
Epoch 49/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 27.9442
Epoch 50/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 27.8969
Epoch 51/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 27.8389
Epoch 52/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 27.7930
Epoch 53/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 27.7463
Epoch 54/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 27.6964
Epoch 55/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 27.6537
Epoch 56/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 27.6150
Epoch 57/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 27.5707
Epoch 58/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 27.5331
Epoch 59/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 27.4965
Epoch 60/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 27.4561
Epoch 61/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 27.4211
Epoch 62/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 27.3905
Epoch 63/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 27.3648
Epoch 64/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 27.3307
Epoch 65/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 27.3065
Epoch 66/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 27.2745
Epoch 67/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 27.2496
Epoch 68/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 27.2236
Epoch 69/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 27.1990
Epoch 70/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 27.1762
Epoch 71/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 27.1534
Epoch 72/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 27.1343
Epoch 73/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 27.1151
Epoch 74/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 27.0895
Epoch 75/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 27.0713
Epoch 76/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 27.0526
Epoch 77/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 27.0354
Epoch 78/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 27.0160
Epoch 79/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 26.9964
Epoch 80/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 26.9820
Epoch 81/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 26.9644
Epoch 82/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 26.9510
Epoch 83/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 26.9325
Epoch 84/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 26.9171
Epoch 85/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 26.9048
Epoch 86/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 26.8892
Epoch 87/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 26.8770
Epoch 88/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 26.8666
Epoch 89/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 26.8533
Epoch 90/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 26.8400
Epoch 91/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 26.8271
Epoch 92/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 26.8180
Epoch 93/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 26.8065
Epoch 94/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 26.7963
Epoch 95/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 26.7866
Epoch 96/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 26.7759
Epoch 97/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 26.7712
Epoch 98/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 26.7596
Epoch 99/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 26.7499
Epoch 100/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 26.7433
Epoch 101/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 26.7318
Epoch 102/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 26.7262
Epoch 103/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 26.7179
Epoch 104/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 26.7109
Epoch 105/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 26.7034
Epoch 106/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 26.6955
Epoch 107/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 26.6886
Epoch 108/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 26.6824
Epoch 109/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 26.6796
Epoch 110/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 26.6703
Epoch 111/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 26.6656
Epoch 112/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 26.6638
Epoch 113/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 26.6539
Epoch 114/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 26.6468
Epoch 115/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 26.6429
Epoch 116/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 26.6362
Epoch 117/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 26.6319
Epoch 118/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 26.6268
Epoch 119/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 26.6213
Epoch 120/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 26.6165
Epoch 121/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 26.6120
Epoch 122/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 26.6088
Epoch 123/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 26.6028
Epoch 124/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 26.5997
Epoch 125/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 26.5939
Epoch 126/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 26.5780
Epoch 127/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 26.5096
Epoch 128/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 26.4710
Epoch 129/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 26.4312
Epoch 130/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 26.3901
Epoch 131/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 26.3213
Epoch 132/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 25.9857
Epoch 133/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 25.6082
Epoch 134/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 25.2966
Epoch 135/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 25.0350
Epoch 136/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 24.8794
Epoch 137/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 24.5685
Epoch 138/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 24.0954
Epoch 139/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 23.7278
Epoch 140/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 23.0581
Epoch 141/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 22.3256
Epoch 142/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step - loss: 21.5363
Epoch 143/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 18.6640
Epoch 144/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 13.5900
Epoch 145/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 9.3768
Epoch 146/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 5.3390
Epoch 147/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 5.2351
Epoch 148/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 6.4785
Epoch 149/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 2.0737
Epoch 150/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 3.8406
Epoch 151/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 3.8306
Epoch 152/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 1.6136
Epoch 153/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 2.3326
Epoch 154/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 2.0240
Epoch 155/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 1.1605
Epoch 156/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 1.7681
Epoch 157/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 1.5967
Epoch 158/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 1.2430
Epoch 159/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 1.6093
Epoch 160/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 1.3369
Epoch 161/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 1.1030
Epoch 162/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 1.3108
Epoch 163/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 1.1829
Epoch 164/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 1.0317
Epoch 165/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 1.1268
Epoch 166/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 1.1160
Epoch 167/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - loss: 0.9983
Epoch 168/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 1.1038
Epoch 169/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 1.0673
Epoch 170/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 1.0271
Epoch 171/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 1.0339
Epoch 172/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.9945
Epoch 173/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.9928
Epoch 174/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - loss: 1.0013
Epoch 175/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 0.9309
Epoch 176/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - loss: 0.9503
Epoch 177/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.9587
Epoch 178/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.9009
Epoch 179/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.8991
Epoch 180/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8987
Epoch 181/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.8621
Epoch 182/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.8734
Epoch 183/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8708
Epoch 184/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8346
Epoch 185/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8432
Epoch 186/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8696
Epoch 187/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8543
Epoch 188/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.8432
Epoch 189/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8311
Epoch 190/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8459
Epoch 191/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.8437
Epoch 192/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.8062
Epoch 193/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.8135
Epoch 194/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.8259
Epoch 195/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8037
Epoch 196/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8229
Epoch 197/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.8176
Epoch 198/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8127
Epoch 199/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8345
Epoch 200/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.8105
Epoch 201/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8086
Epoch 202/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.7963
Epoch 203/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step - loss: 0.7914
Epoch 204/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7994
Epoch 205/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.7958
Epoch 206/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.8066
Epoch 207/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.7909
Epoch 208/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7805
Epoch 209/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7810
Epoch 210/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7961
Epoch 211/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7884
Epoch 212/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7908
Epoch 213/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7859
Epoch 214/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.7850
Epoch 215/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7860
Epoch 216/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7810
Epoch 217/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7981
Epoch 218/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.8308
Epoch 219/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7888
Epoch 220/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8005
Epoch 221/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7838
Epoch 222/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7867
Epoch 223/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7615
Epoch 224/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7777
Epoch 225/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step - loss: 0.7626
Epoch 226/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7717
Epoch 227/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7645
Epoch 228/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7548
Epoch 229/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7817
Epoch 230/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7627
Epoch 231/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.7907
Epoch 232/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7838
Epoch 233/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.8125
Epoch 234/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.7883
Epoch 235/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7589
Epoch 236/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.7855
Epoch 237/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7716
Epoch 238/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7486
Epoch 239/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7704
Epoch 240/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.7596
Epoch 241/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.7490
Epoch 242/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7527
Epoch 243/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7515
Epoch 244/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7704
Epoch 245/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.7503
Epoch 246/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step - loss: 0.7619
Epoch 247/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7616
Epoch 248/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.7329
Epoch 249/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7409
Epoch 250/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.7900
Epoch 251/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7288
Epoch 252/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.7374
Epoch 253/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7540
Epoch 254/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7226
Epoch 255/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7413
Epoch 256/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7726
Epoch 257/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7323
Epoch 258/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7250
Epoch 259/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7602
Epoch 260/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7312
Epoch 261/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 0.7385
Epoch 262/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7575
Epoch 263/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.7519
Epoch 264/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7214
Epoch 265/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7710
Epoch 266/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.7527
Epoch 267/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step - loss: 0.7491
Epoch 268/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 0.7722
Epoch 269/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7567
Epoch 270/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7238
Epoch 271/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7122
Epoch 272/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7593
Epoch 273/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7202
Epoch 274/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7123
Epoch 275/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7327
Epoch 276/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7225
Epoch 277/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.7289
Epoch 278/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7348
Epoch 279/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7433
Epoch 280/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7441
Epoch 281/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7192
Epoch 282/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7518
Epoch 283/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7191
Epoch 284/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7014
Epoch 285/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7361
Epoch 286/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7388
Epoch 287/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7046
Epoch 288/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.7025
Epoch 289/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 0.6997
Epoch 290/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7237
Epoch 291/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 0.7077
Epoch 292/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.7201
Epoch 293/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.7178
Epoch 294/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 0.7078
Epoch 295/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 0.6990
Epoch 296/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7252
Epoch 297/500
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.7155
Epoch 298/500

In [ ]:
from sklearn.model_selection import train_test_split as tts
X_train ,X_test , Y_train , Y_test = tts(x , y, test_size=0.2)

In [128]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

y_pred = model0.predict(X_test)
mae = mean_absolute_error(Y_test, y_pred)
rmse = np.sqrt(mean_squared_error(Y_test, y_pred))
r2 = r2_score(Y_test, y_pred)
mae , rmse , r2

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step

(0.480245568202092, np.float64(0.5616550561870101), 0.700055519513147)

In [125]:
dic = {
    "budeget_milion" : np.random.randint(100,700),
    "worldwide_gross_milion" : np.random.randint(100, 700),
    "genre" : np.random.randint(1 ,4),
    "director_experience" : np.random.randint(0,10),
    "runtime_min" : np.random.randint(100,180),
    "release_season" : 2,
    "sequel" : 1
}
dfr = pd.DataFrame(dic, index=[1])
dfr

,budeget_milion,worldwide_gross_milion,genre,director_experience,runtime_min,release_season,sequel
1,196,214,1,2,148,2,1

In [126]:
r = model.predict(dfr)
print(r)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step
[[7.0435123]]